.TH "src Directory Reference" 3 "Mon Feb 22 2021" "Symmetric matrix eigenvalues calculation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBinclusions\&.h\fP"
.br
.ti -1c
.RI "file \fBjacobi\&.c\fP"
.br
.ti -1c
.RI "file \fBmain\&.c\fP"
.br
.ti -1c
.RI "file \fBmatrix\&.c\fP"
.br
.in -1c
