.TH "src/jacobi.c" 3 "Sat Mar 6 2021" "Symmetric matrix eigenvalues calculation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/jacobi.c
.SH SYNOPSIS
.br
.PP
\fC#include 'inclusions\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "size_t \fBjacobi\fP (size_t n, double M[][n])"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "size_t jacobi (size_t n, double M[][n])"

.SH "Author"
.PP 
Generated automatically by Doxygen for Symmetric matrix eigenvalues calculation from the source code\&.
