.TH "main" 3 "Sat Mar 6 2021" "Symmetric matrix eigenvalues calculation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
main
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "list \fBfile\fP = [input('dir : '), input('file name : ')]"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "list file = [input('dir : '), input('file name : ')]"

.SH "Author"
.PP 
Generated automatically by Doxygen for Symmetric matrix eigenvalues calculation from the source code\&.
