.TH "src/matrix.c" 3 "Sat Mar 6 2021" "Symmetric matrix eigenvalues calculation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/matrix.c
.SH SYNOPSIS
.br
.PP
\fC#include 'inclusions\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "double(* \fBmat_eye\fP (const size_t dim))[]"
.br
.ti -1c
.RI "int \fBmat_zeros\fP (size_t n, size_t m, double *mat)"
.br
.ti -1c
.RI "void \fBwelcom_msg\fP (const char *msg)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "double(* mat_eye (const size_t dim))[]"
Returns the square Identy matrix of dimension dim 
.PP
\fBParameters\fP
.RS 4
\fIdim\fP : the dimension of the matrix 
.RE
.PP
\fBReturns\fP
.RS 4
Return a pointer to a dim-by-dim matrix M[dim][dim] dynamically allocated\&. The pointer type is : (double *)[dim]
.RE
.PP

.SS "int mat_zeros (size_t n, size_t m, double * mat)"
Sets to zero all the elements of n-by-m matrix mat 
.PP
\fBReturns\fP
.RS 4
1 if succeed, 0 instead\&.
.RE
.PP

.SS "void welcom_msg (const char * msg)"
\\function \fBwelcom_msg(const char *msg)\fP Display msg content as a banner 
.PP
\fBParameters\fP
.RS 4
\fImsg\fP character string to display
.RE
.PP
Displays the content of the msg character string into a banner\&. Serves as welcome message
.SH "Author"
.PP 
Generated automatically by Doxygen for Symmetric matrix eigenvalues calculation from the source code\&.
